/**
 * Amplify Chat Backend Configuration Template
 *
 * This is a TEMPLATE file for local development.
 *
 * FOR DEPLOYMENT:
 * - This file is AUTO-GENERATED by publish.py
 * - It is replaced on every deployment with the actual KB ID from the SAM stack
 * - Do NOT commit the generated version to git
 *
 * FOR LOCAL DEVELOPMENT:
 * 1. Copy this file to config.ts: cp amplify/data/config.template.ts amplify/data/config.ts
 * 2. Replace "YOUR_KNOWLEDGE_BASE_ID_HERE" with your actual Bedrock KB ID
 * 3. Or set KNOWLEDGE_BASE_ID env var: export KNOWLEDGE_BASE_ID="your-kb-id"
 * 4. Run: npx ampx sandbox
 */

export const KNOWLEDGE_BASE_CONFIG = {
  // Bedrock Knowledge Base ID
  // Find this in:
  //   - SAM deployment output (KnowledgeBaseId)
  //   - AWS Console > Bedrock > Knowledge bases > [Your KB] > Details
  // Example: "A7B4C9D2E1F6G3H9"
  knowledgeBaseId: process.env.KNOWLEDGE_BASE_ID || "YOUR_KNOWLEDGE_BASE_ID_HERE",

  // AWS Region where Bedrock Knowledge Base is deployed
  // Usually: us-east-1, us-west-2, etc.
  region: process.env.AWS_REGION || "us-east-1",
} as const;

// Type-safe export for use in resource.ts
export type KnowledgeBaseConfig = typeof KNOWLEDGE_BASE_CONFIG;
