/**
 * Amplify Chat Backend Configuration
 *
 * This file is auto-generated by publish.py during deployment.
 * It contains the Knowledge Base ID from the SAM stack and AWS region configuration.
 *
 * DO NOT edit manually - changes will be overwritten on next deployment.
 */

export const KNOWLEDGE_BASE_CONFIG = {
  // Bedrock Knowledge Base ID from SAM deployment
  // Retrieved from CloudFormation stack outputs
  knowledgeBaseId: "LTHSSWBOXT",

  // AWS Region where Bedrock Knowledge Base is deployed
  region: "us-west-2",

  // ConfigurationTable name for runtime config reading
  // Amplify Lambda reads chat settings from this table
  configurationTableName: "amplify-test-11-config-hzb31",

  // Cognito User Pool (from SAM stack)
  // Used by Lambda Authorizer for JWT validation when requireAuth is enabled
  userPoolId: "us-west-2_P7XMxuVJY",
  userPoolClientId: "3gghkg38kesqafldotcpbdeks8",

  // Web component source location (for CodeBuild)
  // CodeBuild downloads and extracts this zip to build the component
  webComponentSourceBucket: "amplify-test-11-artifacts-631094035453",
  webComponentSourceKey: "web-component-source-1762323960.zip",
} as const;

// Type-safe export for use in resource.ts
export type KnowledgeBaseConfig = typeof KNOWLEDGE_BASE_CONFIG;
