/**
 * Amplify Chat Backend Configuration
 *
 * This file is auto-generated by publish.py during deployment.
 * The checked-in version uses placeholders for local development.
 *
 * DO NOT edit manually - changes will be overwritten on next deployment.
 *
 * IMPORTANT: During deployment, publish.py generates the real config with:
 * - knowledgeBaseId: From SAM stack
 * - region: From deployment args
 * - configurationTableName: From SAM stack outputs
 * - webComponentSourceBucket: Artifact bucket name
 * - webComponentSourceKey: Generated timestamp-based key
 */

export const KNOWLEDGE_BASE_CONFIG = {
  // Bedrock Knowledge Base ID from environment or placeholder
  knowledgeBaseId: process.env.KNOWLEDGE_BASE_ID || "local-dev-placeholder",

  // AWS Region where Bedrock Knowledge Base is deployed
  region: process.env.AWS_REGION || "us-east-1",

  // ConfigurationTable name for runtime config reading
  // Amplify Lambda reads chat settings from this table
  configurationTableName: process.env.CONFIGURATION_TABLE_NAME || "placeholder-table",

  // Web component source location (for CodeBuild)
  // CodeBuild downloads and extracts this zip to build the component
  webComponentSourceBucket: process.env.WEB_COMPONENT_SOURCE_BUCKET || "ragstack-placeholder-artifacts",
  webComponentSourceKey: process.env.WEB_COMPONENT_SOURCE_KEY || "placeholder.zip",
} as const;

// Type-safe export for use in resource.ts
export type KnowledgeBaseConfig = typeof KNOWLEDGE_BASE_CONFIG;
