import { defineData, defineFunction } from '@aws-amplify/backend';
import * as path from 'path';
import { KNOWLEDGE_BASE_CONFIG } from './config';

// Define the source extraction tool that Bedrock will call
export const extractSourcesTool = defineFunction({
  name: 'extractSourcesTool',
  entry: path.join(__dirname, 'functions', 'extractSources.ts'),
});

export const data = defineData({
  routes: {
    // Main conversation route for chat
    conversation: {
      // Model: us.anthropic.claude-haiku-4-5-20251001-v1:0 (Haiku)
      // This matches the default model in SAM's ConfigurationTable (chat_model_id)
      // When users change the model in Settings UI, the SAM system uses that configuration.
      //
      // TODO: Implement dynamic model selection (GitHub Issue #XXX)
      // Future enhancement: Read model ID from KNOWLEDGE_BASE_CONFIG or ConfigurationTable
      // to allow users to switch models without redeployment
      // See: docs/OPTIMIZATION.md for details on model selection strategy
      model: 'us.anthropic.claude-haiku-4-5-20251001-v1:0',

      // System prompt - tells the model how to behave
      systemPrompt: `You are a helpful assistant that answers questions about documents in the knowledge base.

When answering:
1. Base your answers on information from the knowledge base
2. If asked about something not in the knowledge base, say so
3. Be concise and clear
4. If multiple sources could answer the question, cite all of them

You have access to a knowledge base containing important documents. Use it to provide accurate, sourced answers.`,

      // Tools that Bedrock can call - includes source extraction
      tools: [extractSourcesTool],

      // Knowledge Base configuration from amplify/data/config.ts
      // Auto-generated by publish.py during deployment
      // This configuration is retrieved from the SAM CloudFormation stack
      bedrockKnowledgeBaseConfig: {
        knowledgeBaseId: KNOWLEDGE_BASE_CONFIG.knowledgeBaseId,
      },
    },
  },

  // Who can access the API
  authorizationModes: {
    defaultAuthorizationMode: 'userPool',  // Users must be logged in
  },
});

// Export for use in backend.ts
export default data;
