/**
 * Auto-generated SAM API Configuration
 *
 * This file is generated by scripts/inject-amplify-config.js during build.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * For local development, this stub provides defaults.
 * In production, CodeBuild regenerates this with actual values.
 */
