/**
 * Auto-generated SAM API Configuration
 *
 * This file is generated by scripts/inject-amplify-config.js during build.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * For local development, this stub provides defaults.
 * In production, CodeBuild regenerates this with actual values.
 */

/**
 * Theme configuration embedded at build time (fallback defaults)
 *
 * These defaults are used if runtime theme fetching fails.
 * Can be overridden per-instance using attributes on <ragstack-chat>.
 */
export const THEME_CONFIG = {
  themePreset: 'light',
  themeOverrides: {}
} as const;
