/**
 * Auto-generated SAM API Configuration
 *
 * This file is generated by scripts/inject-amplify-config.js during build.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated: 2026-01-09T19:56:20.872Z
 */

/**
 * SAM Stack GraphQL API endpoint and API key
 * Used by ChatInterface to query the knowledge base
 */
declare const SAM_GRAPHQL_ENDPOINT: string;
declare const SAM_GRAPHQL_API_KEY: string;

/**
 * Theme configuration embedded at build time (fallback defaults)
 *
 * These defaults are used if runtime theme fetching fails.
 * Can be overridden per-instance using attributes on <ragstack-chat>.
 */
export const THEME_CONFIG = {
  "themeOverrides": {}
} as const;
