/**
 * Template Amplify Configuration
 *
 * This template is used for CI/typecheck when the generated config doesn't exist.
 * The actual config is generated by scripts/inject-amplify-config.js during build.
 *
 * To generate the real config, run the build or deploy process.
 */

export const AMPLIFY_OUTPUTS = {
  version: "1",
  auth: {
    aws_region: "us-east-1",
    user_pool_id: "placeholder",
    user_pool_client_id: "placeholder",
    identity_pool_id: "placeholder",
    unauthenticated_identities_enabled: true,
    mfa_methods: [] as string[],
    standard_required_attributes: [] as string[],
    username_attributes: ["email"],
    user_verification_types: ["email"],
    mfa_configuration: "NONE",
    password_policy: {
      min_length: 8,
      require_lowercase: true,
      require_numbers: true,
      require_symbols: true,
      require_uppercase: true,
    },
  },
  data: {
    url: "https://placeholder.appsync-api.us-east-1.amazonaws.com/graphql",
    aws_region: "us-east-1",
    api_key: "",
    default_authorization_type: "AWS_IAM",
    authorization_types: ["AWS_IAM", "AWS_LAMBDA"],
  },
} as const;

/**
 * Theme configuration - defaults used when no config is generated
 */
export const THEME_CONFIG = {
  themePreset: "light" as const,
  themeOverrides: {} as Record<string, unknown>,
};

/**
 * Optional theme API config - may not exist until SAM stack is deployed
 */
export const THEME_API_CONFIG: { endpoint?: string; apiKey?: string } | undefined = undefined;
